# Generated by Django 4.2.5 on 2024-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='NYC', max_length=100),
            preserve_default=False,
        ),
    ]
